#!/bin/bash
# Manual single-run SIPp test for debugging audio/signaling.
# Runs in the FOREGROUND (no -bg) so you can watch what happens.
#
# Usage: ./manual_test.sh [num_calls]
#   num_calls defaults to 1
#
# manual.csv format (same as device CSVs generated by server.js):
#   RANDOM
#   Display Name;sipuser@domain;domain;[authentication username=sipuser password=secret]
#   Example:
#   RANDOM
#   Test User;1001@example.com;example.com;[authentication username=1001 password=secret]

BASE_DIR="/usr/local/NetSapiens/netsapiens-loadgenerator"
source "$BASE_DIR/.env"

NUMCALLS=${1:-1}

SUT=${TARGET_SERVER}
PRIVATEIP=$(ip a s | sed -ne '/127.0.0.1/!{s/^[ \t]*inet[ \t]*\([0-9.]\+\)\/.*$/\1/p}' | head -1)

INPUTFILE="$BASE_DIR/sipp/csv/manual.csv"

if [ ! -f "$INPUTFILE" ]; then
    echo "ERROR: $INPUTFILE not found"
    echo ""
    echo "Create it with this format:"
    echo "  RANDOM"
    echo "  Display Name;sipuser@domain;domain;authuser;password"
    exit 1
fi

SIP_PORT=20100
MEDIA_PORT=24100
CONTROL_PORT=22100

echo "========================================"
echo "Manual SIPp test"
echo "  Target:     $SUT"
echo "  Local IP:   $PRIVATEIP"
echo "  Input:      $INPUTFILE"
echo "  Calls:      $NUMCALLS"
echo "  SIP port:   $SIP_PORT"
echo "  Media port: $MEDIA_PORT"
echo "========================================"
echo ""

sipp "$SUT" \
    -key expires 60 \
    -r 1 -m "$NUMCALLS" -l "$NUMCALLS" \
    -t u1 \
    -p $SIP_PORT \
    -cp $CONTROL_PORT \
    -mp $MEDIA_PORT \
    -i "$PRIVATEIP" \
    -mi "$PRIVATEIP" \
    -sf "$BASE_DIR/sipp/scripts/register_then_accept.sipp.xml" \
    -oocsf "$BASE_DIR/sipp/scripts/register_then_accept_opus.sipp.xml" \
    -inf "$INPUTFILE" \
    -inf "$BASE_DIR/sipp/csv/random_user_agents.csv" \
    -recv_timeout 60000 \
    -watchdog_interval 0 \
    -aa -default_behaviors -abortunexp \
    -trace_msg \
    -trace_stat -stf /tmp/manual_test_$$.csv -fd 5
